site_name: DnD Player Notes
site_url: https://conorb.one/dnd-player-notes/

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - search.suggest

plugins:
  - search
  - obsidian-support
  - mkdocs-pdf
  - pub-obsidian:
      backlinks:
        enabled: true
      callouts:
        enabled: true
        indentation: spaces
      links:
        wikilinks_enabled: true
        img_lazy: true

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - toc:
      permalink: true
